import styles from "../../styles/modules/News.module.scss";
import Image from "next/image";
import NewsData from "../../public/data/news/news.json";
import Link from "next/link";
import Head from "next/head";

const News = () => {
    const news = NewsData;
    return (
        <>
            <Head itemScope itemType="http://schema.org/WPHeader">
                <title itemProp="headline">Наши события</title>
                <meta
                    itemProp="description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    itemProp="keywords"
                    name="keywords"
                    content="ключевые_слова_для_страницы"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.fullNews}>
                <div
                    itemScope
                    itemType="http://schema.org/Blog"
                    className={`container`}
                >
                    <h1
                        itemProp="description"
                        className={`${styles.title} stn-title`}
                    >
                        Наши события
                    </h1>
                    <div className={styles.wrapper}>
                        {news.map((item, index) => (
                            <Link key={index} href={`/news/${item.id}`}>
                                <a>
                                    <article
                                        itemProp="blogPosts"
                                        itemScope
                                        itemType="http://schema.org/BlogPosting"
                                        className={styles.newsBlock}
                                    >
                                        <div className={styles.imgBlock}>
                                            <Image
                                                alt="news-preview"
                                                src={item.imgSrc}
                                                layout="fill"
                                                objectFit="cover"
                                                itemProp="image"
                                            />
                                        </div>
                                        <div className={styles.imgMobile}>
                                            <Image
                                                alt="news-preview"
                                                src={item.imgSrc}
                                                width={680}
                                                height={500}
                                                itemProp="image"
                                            ></Image>
                                        </div>
                                        <div className={styles.flex}>
                                            <time
                                                itemProp="datePublished"
                                                dateTime={`${item.date}`}
                                                className={styles.date}
                                            >
                                                {item.date}
                                            </time>
                                            <div>
                                                <h3
                                                    itemProp="headline"
                                                    className={`${styles.caption}`}
                                                >
                                                    {item.title}
                                                </h3>
                                                <p
                                                    itemProp="description"
                                                    className={`stn-text`}
                                                >
                                                    {item.shortDescr}
                                                </p>
                                            </div>
                                            <div className={styles.icon}>
                                                <svg
                                                    width="44"
                                                    height="44"
                                                    viewBox="0 0 44 44"
                                                    fill="none"
                                                    xmlns="http://www.w3.org/2000/svg"
                                                >
                                                    <path
                                                        d="M8.66667 2H42V35.3333M42 2L2 42L42 2Z"
                                                        stroke="#313748"
                                                        strokeWidth="4"
                                                        strokeLinecap="round"
                                                        strokeLinejoin="round"
                                                    />
                                                </svg>
                                            </div>
                                        </div>
                                    </article>
                                </a>
                            </Link>
                        ))}
                    </div>
                </div>
            </section>
        </>
    );
};

export default News;
