import Head from "next/head";
import History from "../components/modules/History";
import PreviewBlock from "../components/modules/PreviewBlock";
import Hero from "../components/corporate-ussr/Hero";
import Space from "../components/modules/Space";

// DATA
import EraData from "../public/data/corporate-ussr/era.json";
import OurSpaceData from "../public/data/corporate-ussr/our-space.json";
import YourSpaceData from "../public/data/corporate-ussr/your-space.json";
import ActivityData from "../public/data/corporate-ussr/activity.json";
import QuestData from "../public/data/corporate-ussr/quest.json";
import EatData from "../public/data/corporate-ussr/eat.json";
import SpaceData from "../public/data/home/space.json";
import Questions from "../components/corporate-ussr/Questions";

export default function corporateUSSR() {
    return (
        <>
            <Head itemScope itemType="http://schema.org/WPHeader">
                <title itemProp="headline">Мероприятия СССР</title>
                <meta
                    itemProp="description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    itemProp="keywords"
                    name="keywords"
                    content="ключевые_слова_для_страницы"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <History obj={EraData} />
            <Space obj={OurSpaceData} />
            <Space obj={YourSpaceData} />
            <PreviewBlock obj={ActivityData} type="light" />
            <PreviewBlock obj={QuestData} type="green" />
            <PreviewBlock obj={EatData} type="light" />
            <Space obj={SpaceData} />
            <Questions />
        </>
    );
}
