import Head from "next/head";
import Hero from "../components/about/Hero";

export default function corporateUSSR() {
    return (
        <>
            <Head>
                <title>О нас</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
        </>
    );
}
