import Head from "next/head";
import Hero from "../components/about/Hero";
import Souvenirs from "../components/about/Souvenirs";
import Tickets from "../components/modules/Tickets";

// DATA
import SouvenirsData from "../public/data/about/souvenirs.json";

export default function corporateUSSR() {
    return (
        <>
            <Head>
                <title>О нас</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Souvenirs obj={SouvenirsData["souvenirs"]} />
            <Tickets />
        </>
    );
}
